### ISSUE TITLE
Query regarding the input to RL model

### ISSUE THREAD

**Issue by ashok-arora** [basiclab/TTSG#2]
Hi,
Great work!

I saw this video on the project website:
https://github.com/user-attachments/assets/12f0fc17-aaf6-4df5-8308-c69ea54eafbf
Does the generated scene also have partial observability for the controllable agent?

**Comment by Justin900429** [comment]
Hi, our codebase only supports views from ego-agent. However, adding views from other controllable agents is also possible since this only requires extra listener attached to these agents. Hope this helps!
